### ISSUE TITLE
Bot warrnings

### ISSUE THREAD

**Issue by zmechu** [Ananaskirsche/ts-csgo-rankbot#4]
As I see bot seems to ready to use :-)

Is this warnings are worth of interest?

```
WARNING: Abstract#getCache() is deprecated please use the respective getters
WARNING: you can find a list of available getters on https://multivit4min.github.io/TS3-NodeJS-Library/#teamspeakclient
[2019-09-18 15:14:14] [TeamspeakHelper.js] [debug]: Client GameTracker just connected
(node:13237) UnhandledPromiseRejectionWarning: Error: invalid client type
    at Command.getError (/root/ts-csgo-rankbot/node_modules/ts3-nodejs-library/src/transport/Command.js:143:12)
    at TS3Query.handleQueryError (/root/ts-csgo-rankbot/node_modules/ts3-nodejs-library/src/transport/TS3Query.js:142:44)
    at TS3Query.handleLine (/root/ts-csgo-rankbot/node_modules/ts3-nodejs-library/src/transport/TS3Query.js:116:12)
    at RAW.emit (events.js:198:13)
    at lines.forEach.line (/root/ts-csgo-rankbot/node_modules/ts3-nodejs-library/src/transport/protocols/raw.js:81:32)
    at Array.forEach (<anonymous>)
    at RAW._handleData (/root/ts-csgo-rankbot/node_modules/ts3-nodejs-library/src/transport/protocols/raw.js:81:11)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:265:13)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
(node:13237) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 119)
```

**Comment by Acu1ty** [comment]
Hi @zmechu how can i start the bot?
